---
title: "Parking Tickets"
author: "Jonathan Kacvinsky"
date: "01-31-2026"
format: 
  pdf:
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
include-before-body:
  text: |
    \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
      showspaces = false,
      showtabs = false,
      breaksymbolleft={},
      breaklines
    }
output:
  echo: false
  eval: false
---

"This submission is my work alone and complies with the 30538 integrity policy." Add your initials to indicate your agreement: JK

Before you begin this problem set, please rename `ps3_template.qmd` as `ps3.qmd`.

Please submit correctly and rename ps3_template.qmd as ps3.qmd. Knit your completed solution `ps3.qmd` to make `ps3.pdf`. Push both `ps3.qmd` and `ps3.pdf` to your Github repo. 

```{python}
import os

print(os.getcwd())
new_path = r"c:\Users\home-admin\Documents\University of Chicago\Data Analytics and Visualization for Public Policy"
os.chdir(new_path)
```

```{python}
import pandas as pd
import altair as alt
import time

import warnings 
warnings.filterwarnings('ignore')
alt.renderers.enable("png")
alt.data_transformers.disable_max_rows()

park = pd.read_csv("parking_tickets_one_percent.csv", index_col=0)
park

```

## Data cleaning continued
\
We would like to hear how you used AI (if at all) on this section. Where did you find it useful/not useful? We are asking for knowledge-sharing purposes; your answer will not impact your grade on the assignment.
\
Answer:
\
1.  The old violation code was a $120 fine, the new is a $200 fine.
2.  $60 for street cleaning citation, $50 for expired meter citation, $75-$135 for large passenger vehicles, $60 for late city sticker purchase    

## Revenue increase from "missing city sticker" tickets
\
We would like to hear how you used AI (if at all) on this section. Where did you find it useful/not useful? We are asking for knowledge-sharing purposes; your answer will not impact your grade on the assignment.
\
Answer: I used AI to fix my to_period("M").dt.to_timestamp() organization of monthly rows.
I also used it to help calculate repayment rates and to translate that to revenue gained per ticket.
\
1. 
```{python}

park["violation_missing"] = np.where(
    park["violation_code"].isin(["0964125", "0964125B"]),
    "Missing City Sticker",
    "Other"
)

park["issue_date"] = pd.to_datetime(park["issue_date"])
park["month"] = park["issue_date"].dt.to_period("M").dt.to_timestamp()

month_missing = (park[park["violation_missing"] == "Missing City Sticker"].groupby("month").size().reset_index(name="count"))

alt.Chart(month_missing).mark_line().encode(
    alt.X("month:T", title="Month"),
    alt.Y("count:Q", title = "Mising City Sticker Citation"),
).properties(
    width=700,
    height=200,
    title="Missing City Sticker Citation by Month"
)
```

2. 
```{python}

alt.Chart(month_missing).mark_line().encode(
    alt.X("month:T", title="Month", axis=alt.Axis(format="%Y-%m", tickCount="month", labelAngle=-75)),
    alt.Y("count:Q", title="Mising City Sticker Citation"),
).properties(
    width=1000,
    height=300,
    title="Missing City Sticker Citation by Month"
)

```

#Website used: altair-viz.github.io/user_guide/customization.html

3. 
```{python}
park_2013 = park[
    (park["issue_date"] >= "2013-01-01") &
    (park["issue_date"] < "2014-01-01") &
    (park["violation_code"].isin(["0964125", "0964125B"]))
]
print(f"Projected Revenue After Citation Increase: ${len(park_2013) * 80 * 100}")
```

4.

```{python}
park_2014 = park[
    (park["issue_date"] >= "2014-01-01") &
    (park["issue_date"] < "2015-01-01") &
    (park["violation_code"].isin(["0964125", "0964125B"])) &
    (park["ticket_queue"] == "Paid")
]

print(f"Actual Revenue After Citation Increase: ${park_2014["total_payments"].sum() * 100}")
```

5.

```{python}
miss_stick = park[park["violation_code"].isin(["0964125", "0964125B"])].copy()
miss_stick["month"] = miss_stick["issue_date"].dt.to_period("M").dt.to_timestamp()
repay_rate = (miss_stick.groupby("month").agg(fine_amount=("fine_level1_amount","sum"), tot_pay=("total_payments", "sum")).reset_index())
repay_rate["repayment_rate"] = (repay_rate["tot_pay"]/repay_rate["fine_amount"])

re_ra = alt.Chart(repay_rate).mark_line().encode(
    alt.X("month:T", title="Month", axis=alt.Axis(format="%Y-%m", tickCount="month", labelAngle=-75)),
    alt.Y("repayment_rate:Q", title = "Repayment Rate"),
).properties(
    width=1000,
    height=300,
    title="Repayment Rates on Missing City Stickers"
)

pol_change = (
    alt.Chart(pd.DataFrame({"month": ["2014-01-01"]}))
    .mark_rule(
        color="red"
    )
    .encode(
        x = "month:T"
    )
)

re_ra + pol_change

```

#After the policy was introduced, repayment rates dropped.

6.

```{python}
viol_types = park[
    (park["issue_date"] >= "2014-01-01") &
    (park["issue_date"] < "2015-01-01") &
    (park["violation_description"].isin(["DISABLED PARKING ZONE", "DOUBLE PARKING OR STANDING", "WITHIN 15' OF FIRE HYDRANT"]))
].copy()

recommended = (viol_types.groupby("violation_description").agg(tickets_issued=("violation_code", "count"), total_fines=("fine_level1_amount", "sum"), total_paid=("total_payments", "sum")).reset_index())
recommended["repayment_rate"] = (recommended["total_paid"]/recommended["total_fines"])
recommended["revenue"] = (recommended["total_fines"] * recommended["repayment_rate"])

recommended 

rec_graph = alt.Chart(recommended).mark_bar().encode(
    alt.X("violation_description:N", title="Violation Type"),
    alt.Y("revenue:Q", title = "Expected Revenue per Ticket"),
).properties(
    width=1000,
    height=300,
    title="Revenue Raised by Violation Type"
)

rec_graph

```

#I would recommend increasing the price of parking in disabled parking zones, double parking or standing, and parking within 15' of a fire hydrant.
#These are projections for if the tickets were the same price, but each of these violation types make substantial revenue, and an increase in any of them would make substantial money.
#Even if the money raised isn't as much as it is for city sticker citations, each of these prevent potential security risks for vulnerable populations.


## Headlines and sub-messages
\
We would like to hear how you used AI (if at all) on this section. Where did you find it useful/not useful? We are asking for knowledge-sharing purposes; your answer will not impact your grade on the assignment.
\
Answer: I used ai to help choose a good format for Tooltip.
\
1. 

```{python}

new_park = park.copy()
new_park["paid"] = np.where(park["ticket_queue"] == "Paid", 1, 0)
tot_tick = new_park.groupby("violation_description").agg(tickets_issued=("violation_description", "size"), fraction_paid=("paid", "mean"), avg_fine=("fine_level1_amount", "mean")).reset_index().sort_values("tickets_issued", ascending=False)
print(tot_tick.head())

```

2. 

```{python}
tot_tick_100 = tot_tick[tot_tick["tickets_issued"] >= 100]

alt.Chart(tot_tick_100).mark_circle().encode(
    alt.X("avg_fine:Q", title="Average Level 1 Fine in Dollars"),
    alt.Y("fraction_paid:Q", title="Fraction of Time Ticket is Paid"),
    tooltip=[
        "violation_description:N",
        "tickets_issued:Q",
        alt.Tooltip("fraction_paid:Q", format=".2f"),
        alt.Tooltip("avg_fine:Q", format="$.0f")
    ],
).properties(
    width=500,
    height=200,
    title="Fraction Total Tickets are Paid and their Amounts"
)

#Headline and sub-message: The average amount of level 1 fines in dollars decreases as the fraction of time they are paid.

alt.Chart(tot_tick_100).mark_bar().encode(
    alt.X("avg_fine:Q", title="Average Level 1 Fine in Dollars"),
    alt.Y("fraction_paid:Q", title="Fraction of Time Ticket is Paid"),
    tooltip=[
        "violation_description:N",
        "tickets_issued:Q",
        alt.Tooltip("fraction_paid:Q", format=".2f"),
        alt.Tooltip("avg_fine:Q", format="$.0f")
    ],
).properties(
    width=500,
    height=200,
    title="Fraction Total Tickets are Paid and their Amounts"
)

#Headline and sub-message: The average amount of level 1 fines in dollars decreases as the fraction of time they are paid.

alt.Chart(tot_tick_100).mark_rect().encode(
    alt.X("avg_fine:Q", title="Average Level 1 Fine in Dollars"),
    alt.Y("fraction_paid:Q", title="Fraction of Time Ticket is Paid"),
    tooltip=[
        "violation_description:N",
        "tickets_issued:Q",
        alt.Tooltip("fraction_paid:Q", format=".2f"),
        alt.Tooltip("avg_fine:Q", format="$.0f")
    ],
).properties(
    width=500,
    height=200,
    title="Fraction Total Tickets are Paid and their Amounts"
)

#Headline and sub-message: The average amount of level 1 fines in dollars decreases as the fraction of time they are paid.
```

3. 

#I would choose the bar chart. It has a clear delination of the average level 1 fines, and represents a comparison of their magnitudes well.

## Exploration vs. Production
\
We would like to hear how you used AI (if at all) on this section. Where did you find it useful/not useful? We are asking for knowledge-sharing purposes; your answer will not impact your grade on the assignment.
\
Answer: I used AI to help differentiate my labels and format it properly to highlight just a few violation types.
\
1. 

```{python}
alt.Chart(tot_tick_100).mark_circle().encode(
    alt.X("avg_fine:Q", title="Average Level 1 Fine in Dollars"),
    alt.Y("fraction_paid:Q", title="Fraction of Time Ticket is Paid"),
    color=alt.Color(
        "violation_description:N",
        title="Violation Types"
    ),
    tooltip=[
        "violation_description:N",
        "tickets_issued:Q",
        alt.Tooltip("fraction_paid:Q", format=".2f"),
        alt.Tooltip("avg_fine:Q", format="$.0f")
    ],
).properties(
    width=500,
    height=200,
    title="Fraction Total Tickets are Paid and their Amounts"
)
```

2.

```{python}

tot_tick_100
highlights = (tot_tick_100.sort_values("tickets_issued", ascending=False).head()["violation_description"].tolist())
tot_tick_100["highlights"] = tot_tick_100["violation_description"].isin(highlights)

point = alt.Chart(tot_tick_100).mark_circle().encode(
    alt.X("avg_fine:Q", title="Average Level 1 Fine in Dollars"),
    alt.Y("fraction_paid:Q", title="Fraction of Time Ticket is Paid"),
    tooltip=[
        "violation_description:N",
        "tickets_issued:Q",
        alt.Tooltip("fraction_paid:Q", format=".2f"),
    ]
)

label = alt.Chart(tot_tick_100[tot_tick_100["highlights"]]
).mark_text(
    align="left",
    dx=8,
    dy=-4,
    fontSize=12
).encode(
    alt.X("avg_fine:Q"),
    alt.Y("fraction_paid:Q"),
    text="violation_description:N"
)

(point + label).properties(
    width=500,
    height=200,
    title="Fraction Total Tickets are Paid and their Amounts for Top 5 Violation Types"
)

#A useful way to reduce the clutter of labels is to reduce it to just a highlighted few, so that the reader can interpret the results in a cleaner more efficient manner.

```